version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: debian_pkg
    package_name: "{{ .ProjectName }}"
    formats:
      - deb
    homepage: "https://github.com/pavliha/aptforge"
    maintainer: "Pavlo Kostiuk <kostyk.pavel.09@gmail.com>"
    description: "AptForge automates apt repository management"
    license: "MIT"
    vendor: "pavliha"
    section: default
    priority: optional
    dependencies:
      - bash
      - ca-certificates
    recommends:
      - iproute2
    suggests:
      - traceroute

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: pavliha
    name: aptforge
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Release {{ .Tag }} ({{ .Date }})
    
    Welcome to this new release!
  footer: |
    ## Thanks!
    
    Those were the changes on {{ .Tag }}!
  name_template: "{{.ProjectName}}-v{{.Version}}"

checksum:
  name_template: 'checksums.txt'

publishers:
  - name: aptforge-deploy
    cmd: |
      aptforge --file {{ abs .ArtifactPath }} --bucket aircast-apt --access-key {{ .Env.AWS_ACCESS_KEY_ID }} --secret-key {{ .Env.AWS_SECRET_ACCESS_KEY }} --endpoint s3.amazonaws.com
    checksum: false
    ids:
      - debian_pkg
