name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: GoReleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean --skip=validate
        env:
          API_HOST: ${{ environments.API_HOST }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
